class Broker:
    """
    An abstract class to model the interaction between a set of
    order objects generated by a portfolio and the fill objects
    that occur in the market.
    """

    def __init__(self):
        pass
